### PR TITLE
Support for DigitalOcean Servers via their API

### PR DESCRIPTION
**Pull request by RickBakkr**
I have added support for DigitalOcean servers to be added and controlled from vmDash.

### CODE REVIEW

**Comment by myrsk** [comment]
Thanks for the PR @RickBakkr  !

Appreciate the time you took to integrate DO into vmDash 👍

**Comment by RickBakkr** [comment]
Sure thing! @myrsk
Let me know if there are suggestions for other providers to implement.

**Comment by myrsk** [comment]
Just a question, doesn’t DO api support the other features from the main page, like root pass reset, vnc, rescue, and iso mounts?

I honestly haven’t looked into it yet. 

Regards,
R. Alkhaili

**Comment by RickBakkr** [comment]
No, unfortunately DigitalOcean does not offer any support for VNC or such other features via the API.
Feel free to reference them, in case I have missed them in the docs. Happy to implement further features ;)

**Comment by myrsk** [comment]
Yeah .. never would have guessed that DO's API would be with the bare minimum :P 

The only one I found is : 
https://developers.digitalocean.com/documentation/v2/#password-reset-a-droplet

But this seems that it will send the password via mail, as the response doesn't include it.

I remember there were a couple of other providers that were listed at LET's thread - but I think that I will be working on the bigger providers' API as that would benefit more people to begin with.

Thanks for your contribution again.

**Pull request merged**
